### ISSUE TITLE
Kojelauta jäätyy kun "kokonaiskulutuksen trendit" sivu avataan

### ISSUE THREAD

**Issue by bbtheo** [bbtheo/Shiny_app_datahuone#30]
Kun kojelaudalla avaa sivun "kokonaiskulutuksen trendit" sivu välittömästi jäätyy. 

![image](https://github.com/user-attachments/assets/7373a204-ee24-44ee-97e1-929a84359b8c)

**Comment by bbtheo** [comment]
Vaikuttaa tapahtuvan myös muilla Y&E-osion sivuilla.

**Comment by meerise** [comment]
Login perusteella vika näyttäis johtuvan fingridin apista. Selvitellään!
